dist: xenial
cache:
    directories:
        - $HOME/.cache/pip
        - tests/bot-ci
addons:
    apt:
        packages:
            - libssl1.0.0
            - zsh
            - tcsh
            - mksh
            - busybox
            # - rc
            - socat
            - bc
language: python
install: tests/install.sh
script: tests/test.sh
jobs:
    include:
        - stage: Recent Python
        - python: "3.7"
        - stage: PyPy
          python: "pypy"
        - python: "pypy3"
        - stage: Old Python
          python: "3.4"
        - python: "3.5"
        - python: "3.6"

# vim: et
